# Generated by Django 5.1.2 on 2024-10-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='password',
            new_name='passcode',
        ),
    ]
